### ISSUE TITLE
Stuff ToDo

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Yorot.Standart#1]
- [ ] AppForms
- [ ] Permission System for Apps
- [ ] User settings (& many `YorotManager` classes) should have `SetValue()` for compatibility with permission system and properties inside each class should have only an internal set.
- [x] Resource Manager (for web pages such as error page, Incognito information page etc.)
- [ ] Extension improvement (custom protocols instead of ExpPacks)
- [x] Web Engine feature removal (makes no sense, also we aren't gonna let someone to run PHP or nodejs or etc. in the machine for security, optimization and privacy reasons and engines [mostly CEF related] used by Yorot flavors do good job on caching files loaded from web)
- [x] Download Manager should also track current downloads
- [x] Session Manager
- [ ] Write a filesystem and I/O class so Extensions & Apps should **NOT** use `System.IO` (& warn user if app is trying to use it) , which is a big security problem.
